export interface IItemState {
  id: number;
  name: string;
  cubicFeet: number;
  section: string;
  count: number;
}

export const initialState: Array<IItemState> = [
  {
    id: 0,
    name: "Armchair",
    cubicFeet: 15,
    section: "Lounge / Conservatory",
    count: 0,
  },
  {
    id: 1,
    name: "Bureau",
    cubicFeet: 15,
    section: "Lounge / Conservatory",
    count: 0,
  },
  {
    id: 2,
    name: "Bookself (S)",
    cubicFeet: 15,
    section: "Lounge / Conservatory",
    count: 0,
  },
  {
    id: 3,
    name: "Bookself (L)",
    cubicFeet: 30,
    section: "Lounge / Conservatory",
    count: 0,
  },
  {
    id: 4,
    name: "Carver",
    cubicFeet: 10,
    section: "Lounge / Conservatory",
    count: 0,
  },
  {
    id: 5,
    name: "China Cabinet (S)",
    cubicFeet: 15,
    section: "Lounge / Conservatory",
    count: 0,
  },
  {
    id: 6,
    name: "China Cabinet (L)",
    cubicFeet: 35,
    section: "Lounge / Conservatory",
    count: 0,
  },
  {
    id: 7,
    name: "Grandfather Clock",
    cubicFeet: 20,
    section: "Lounge / Conservatory",
    count: 0,
  },
  {
    id: 8,
    name: "Floor Lamp",
    cubicFeet: 8,
    section: "Lounge / Conservatory",
    count: 0,
  },
  {
    id: 9,
    name: "Occassional Chair",
    cubicFeet: 10,
    section: "Lounge / Conservatory",
    count: 0,
  },
  {
    id: 10,
    name: "Piano Stool",
    cubicFeet: 5,
    section: "Lounge / Conservatory",
    count: 0,
  },
  {
    id: 11,
    name: "Piano Upright",
    cubicFeet: 40,
    section: "Lounge / Conservatory",
    count: 0,
  },
  {
    id: 12,
    name: "Picutre/ Mirror (S)",
    cubicFeet: 1,
    section: "Lounge / Conservatory",
    count: 0,
  },
  {
    id: 13,
    name: "Picture/ Mirror (L)",
    cubicFeet: 3,
    section: "Lounge / Conservatory",
    count: 0,
  },
  {
    id: 14,
    name: "Pouffe",
    cubicFeet: 10,
    section: "Lounge / Conservatory",
    count: 0,
  },
  {
    id: 15,
    name: "Rocking Chair",
    cubicFeet: 20,
    section: "Lounge / Conservatory",
    count: 0,
  },
  {
    id: 16,
    name: "Rug (S)",
    cubicFeet: 5,
    section: "Lounge / Conservatory",
    count: 0,
  },
  {
    id: 17,
    name: "Rug (L)",
    cubicFeet: 10,
    section: "Lounge / Conservatory",
    count: 0,
  },
  {
    id: 18,
    name: "Settee - 1 Seat",
    cubicFeet: 25,
    section: "Lounge / Conservatory",
    count: 0,
  },
  {
    id: 19,
    name: "Settee - 2 Seat",
    cubicFeet: 45,
    section: "Lounge / Conservatory",
    count: 0,
  },
  {
    id: 20,
    name: "Settee - 3 Seat",
    cubicFeet: 60,
    section: "Lounge / Conservatory",
    count: 0,
  },
  {
    id: 21,
    name: "Sideboard (S)",
    cubicFeet: 20,
    section: "Lounge / Conservatory",
    count: 0,
  },
  {
    id: 22,
    name: "Sideboard (L)",
    cubicFeet: 40,
    section: "Lounge / Conservatory",
    count: 0,
  },




  {
    id: 23,
    name: "CD Stand",
    cubicFeet: 5,
    section: "Living Area",
    count: 0,
  },
  {
    id: 24,
    name: "Coffee Table",
    cubicFeet: 10,
    section: "Living Area",
    count: 0,
  },
  {
    id: 25,
    name: "Mirror",
    cubicFeet: 3,
    section: "Living Area",
    count: 0,
  },
  {
    id: 26,
    name: "Music Cabinet",
    cubicFeet: 15,
    section: "Living Area",
    count: 0,
  },
  {
    id: 27,
    name: "Nest Tables",
    cubicFeet: 10,
    section: "Living Area",
    count: 0,
  },
  {
    id: 28,
    name: "Picture/ Mirror (S)",
    cubicFeet: 1,
    section: "Living Area",
    count: 0,
  },
  {
    id: 29,
    name: "Picture/ Mirror (L)",
    cubicFeet: 3,
    section: "Living Area",
    count: 0,
  },
  {
    id: 30,
    name: "Stool",
    cubicFeet: 5,
    section: "Living Area",
    count: 0,
  },
  {
    id: 31,
    name: "TV",
    cubicFeet: 10,
    section: "Living Area",
    count: 0,
  },
  {
    id: 32,
    name: "TV Stand",
    cubicFeet: 10,
    section: "Living Area",
    count: 0,
  },
  {
    id: 33,
    name: "Box / Bag",
    cubicFeet: 5,
    section: "Living Area",
    count: 0,
  },
  



  
  {
    id: 34,
    name: "Bookshelf (S)",
    cubicFeet: 15,
    section: "Dining",
    count: 0,
  },
  {
    id: 35,
    name: "Bookshelf (L)",
    cubicFeet: 30,
    section: "Dining",
    count: 0,
  },
  {
    id: 36,
    name: "Dining Chair",
    cubicFeet: 5,
    section: "Dining",
    count: 0,
  },
  {
    id: 37,
    name: "Dining Table (S)",
    cubicFeet: 30,
    section: "Dining",
    count: 0,
  },
  {
    id: 38,
    name: "Dining Table (M)",
    cubicFeet: 40,
    section: "Dining",
    count: 0,
  },
  {
    id: 39,
    name: "Dining Table (L)",
    cubicFeet: 50,
    section: "Dining",
    count: 0,
  },
  {
    id: 40,
    name: "Picture/ Mirror (S)",
    cubicFeet: 1,
    section: "Dining",
    count: 0,
  },
  {
    id: 41,
    name: "Picture/ Mirror (L)",
    cubicFeet: 3,
    section: "Dining",
    count: 0,
  },
  {
    id: 42,
    name: "Settle Chair",
    cubicFeet: 30,
    section: "Dining",
    count: 0,
  },
  {
    id: 43,
    name: "Church Style Pew",
    cubicFeet: 30,
    section: "Dining",
    count: 0,
  },
  {
    id: 44,
    name: "Sideboard (S)",
    cubicFeet: 20,
    section: "Dining",
    count: 0,
  },
  {
    id: 45,
    name: "Sideboard (M)",
    cubicFeet: 30,
    section: "Dining",
    count: 0,
  },
  {
    id: 46,
    name: "Sideboard (L)",
    cubicFeet: 40,
    section: "Dining",
    count: 0,
  },
  {
    id: 47,
    name: "TV",
    cubicFeet: 10,
    section: "Dining",
    count: 0,
  },
  {
    id: 48,
    name: "Welsh Dresser",
    cubicFeet: 50,
    section: "Dining",
    count: 0,
  },  






  {
    id: 49,
    name: "Bar Stool",
    cubicFeet: 10,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 50,
    name: "Bookshelf (S)",
    cubicFeet: 15,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 51,
    name: "Bookshelf (L)",
    cubicFeet: 30,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 52,
    name: "Butchers Block",
    cubicFeet: 18,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 53,
    name: "Cooker",
    cubicFeet: 18,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 54,
    name: "Clothes Horse",
    cubicFeet: 5,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 55,
    name: "Dishwasher",
    cubicFeet: 18,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 56,
    name: "Dryer",
    cubicFeet: 18,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 57,
    name: "Freezer, Chest",
    cubicFeet: 18,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 58,
    name: "Freezer, Upright",
    cubicFeet: 34,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 59,
    name: "Fridge/Freezer",
    cubicFeet: 36,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 60,
    name: "Fridge - American",
    cubicFeet: 60,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 61,
    name: "Fridge - beer",
    cubicFeet: 5,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 62,
    name: "Fridge - under counter",
    cubicFeet: 18,
    section: "Kitchen / Utility",
    count: 0,
  },
  {
    id: 63,
    name: "High Chair",
    cubicFeet: 10,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 64,
    name: "Ironing Board",
    cubicFeet: 1,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 65,
    name: "Kitchen Cabinet",
    cubicFeet: 40,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 66,
    name: "Kitchen Chair",
    cubicFeet: 10,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 67,
    name: "Kitchen Table (S)",
    cubicFeet: 30,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 68,
    name: "Kitchen Table (L)",
    cubicFeet: 50,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 69,
    name: "Laundy Basket",
    cubicFeet: 15,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 70,
    name: "Microwave",
    cubicFeet: 5,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 71,
    name: "Picture/ Mirror (S)",
    cubicFeet: 1,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 72,
    name: "Picture/ Mirror (L)",
    cubicFeet: 3,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 73,
    name: "Store Cubboard (M)",
    cubicFeet: 10,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 74,
    name: "Tea Trolley",
    cubicFeet: 10,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 75,
    name: "TV",
    cubicFeet: 10,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 76,
    name: "Vacuum Cleaner",
    cubicFeet: 5,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 77,
    name: "Washing Machine",
    cubicFeet: 18,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 78,
    name: "Welsh Dresser",
    cubicFeet: 5,
    section: "Kitchen / Utility",
    count: 0,
  },
  
  




  {
    id: 79,
    name: "Bed Single",
    cubicFeet: 30,
    section: "Bedroom",
    count: 0,
  },
  {
    id: 80,
    name: "Bed Double",
    cubicFeet: 50,
    section: "Bedroom",
    count: 0,
  },
  {
    id: 81,
    name: "Bed Queen",
    cubicFeet: 60,
    section: "Bedroom",
    count: 0,
  },
  {
    id: 82,
    name: "Bed King/ Super King",
    cubicFeet: 90,
    section: "Bedroom",
    count: 0,
  },
  {
    id: 83,
    name: "Bedroom Chair",
    cubicFeet: 10,
    section: "Bedroom",
    count: 0,
  },
  {
    id: 84,
    name: "Bedside Table/ Drawers",
    cubicFeet: 10,
    section: "Bedroom",
    count: 0,
  },
  {
    id: 85,
    name: "Blanket Box / Ottoman",
    cubicFeet: 12,
    section: "Bedroom",
    count: 0,
  },
  {
    id: 86,
    name: "Bookshelf (S)",
    cubicFeet: 15,
    section: "Bedroom",
    count: 0,
  },
  {
    id: 87,
    name: "Bookshelf (L)",
    cubicFeet: 30,
    section: "Bedroom",
    count: 0,
  },
  {
    id: 88,
    name: "Bunk Beds",
    cubicFeet: 50,
    section: "Bedroom",
    count: 0,
  },
  {
    id: 89,
    name: "Chaise Longues",
    cubicFeet: 30,
    section: "Bedroom",
    count: 0,
  },
  {
    id: 90,
    name: "Chest of Drawers (S)",
    cubicFeet: 10,
    section: "Bedroom",
    count: 0,
  },
  {
    id: 91,
    name: "Chest of Drawers (M)",
    cubicFeet: 15,
    section: "Bedroom",
    count: 0,
  },
  {
    id: 92,
    name: "Chest of Drawers (L)",
    cubicFeet: 25,
    section: "Bedroom",
    count: 0,
  },
  {
    id: 93,
    name: "Cot",
    cubicFeet: 25,
    section: "Bedroom",
    count: 0,
  },
  {
    id: 94,
    name: "Dressing Table (S)",
    cubicFeet: 20,
    section: "Bedroom",
    count: 0,
  },
  {
    id: 95,
    name: "Dessing Table (L)",
    cubicFeet: 25,
    section: "Bedroom",
    count: 0,
  },
  {
    id: 96,
    name: "Folding Bed",
    cubicFeet: 10,
    section: "Bedroom",
    count: 0,
  },
  {
    id: 97,
    name: "Folding Cot",
    cubicFeet: 10,
    section: "Bedroom",
    count: 0,
  },
  {
    id: 98,
    name: "Headboard",
    cubicFeet: 10,
    section: "Bedroom",
    count: 0,
  },
  {
    id: 99,
    name: "Linen Basket",
    cubicFeet: 5,
    section: "Bedroom",
    count: 0,
  },
  {
    id: 100,
    name: "Pedestal Cupboard",
    cubicFeet: 10,
    section: "Bedroom",
    count: 0,
  },
  {
    id: 101,
    name: "Picture",
    cubicFeet: 2,
    section: "Bedroom",
    count: 0,
  },
  {
    id: 102,
    name: "Sofa Bed",
    cubicFeet: 40,
    section: "Bedroom",
    count: 0,
  },
  {
    id: 103,
    name: "Suitcase",
    cubicFeet: 5,
    section: "Bedroom",
    count: 0,
  },
  {
    id: 104,
    name: "Tallboy",
    cubicFeet: 15,
    section: "Bedroom",
    count: 0,
  },
  {
    id: 105,
    name: "TV",
    cubicFeet: 10,
    section: "Bedroom",
    count: 0,
  },
  {
    id: 106,
    name: "Trunk",
    cubicFeet: 20,
    section: "Bedroom",
    count: 0,
  },
  {
    id: 107,
    name: "Wardrobe 2'6\"",
    cubicFeet: 25,
    section: "Bedroom",
    count: 0,
  },
  {
    id: 108,
    name: "Wardrobe 3'0\"",
    cubicFeet: 30,
    section: "Bedroom",
    count: 0,
  },
  {
    id: 109,
    name: "Wardrobe 4'6\"",
    cubicFeet: 40,
    section: "Bedroom",
    count: 0,
  },
  {
    id: 110,
    name: "Wardrobe 6'6\"",
    cubicFeet: 60,
    section: "Bedroom",
    count: 0,
  },
  {
    id: 111,
    name: "Wardrobe Box Portable",
    cubicFeet: 8,
    section: "Bedroom",
    count: 0,
  },
  {
    id: 112,
    name: "Box / Bag",
    cubicFeet: 5,
    section: "Bedroom",
    count: 0,
  },



  {
    id: 113,
    name: "Bookcase (S)",
    cubicFeet: 15,
    section: "Office/ Study",
    count: 0,
  },
  {
    id: 114,
    name: "Bookcase (L)",
    cubicFeet: 30,
    section: "Office/ Study",
    count: 0,
  },
  {
    id: 115,
    name: "Bookshelf (per shelf)",
    cubicFeet: 2,
    section: "Office/ Study",
    count: 0,
  },
  {
    id: 116,
    name: "Computer",
    cubicFeet: 10,
    section: "Office/ Study",
    count: 0,
  },
  {
    id: 117,
    name: "Desk (S)",
    cubicFeet: 20,
    section: "Office/ Study",
    count: 0,
  },
  {
    id: 118,
    name: "Desk (L)",
    cubicFeet: 30,
    section: "Office/ Study",
    count: 0,
  },
  {
    id: 119,
    name: "Drawers - Under desk",
    cubicFeet: 10,
    section: "Office/ Study",
    count: 0,
  },
  {
    id: 120,
    name: "Filing Cabinet 2 drawer",
    cubicFeet: 9,
    section: "Office/ Study",
    count: 0,
  },
  {
    id: 121,
    name: "Filing Cabinet 3 drawer",
    cubicFeet: 12,
    section: "Office/ Study",
    count: 0,
  },
  {
    id: 122,
    name: "Filing Cabinet 4 drawer",
    cubicFeet: 18,
    section: "Office/ Study",
    count: 0,
  },
  {
    id: 123,
    name: "Office Chair",
    cubicFeet: 10,
    section: "Office/ Study",
    count: 0,
  },
  {
    id: 124,
    name: "Picture/ Mirror (S)",
    cubicFeet: 1,
    section: "Office/ Study",
    count: 0,
  },
  {
    id: 125,
    name: "Picture/ Mirror (L)",
    cubicFeet: 3,
    section: "Office/ Study",
    count: 0,
  },
  {
    id: 126,
    name: "Sofa Bed",
    cubicFeet: 60,
    section: "Office/ Study",
    count: 0,
  },







  {
    id: 127,
    name: "Free Weights (per item)",
    cubicFeet: 5,
    section: "Exercise Equipment",
    count: 0,
  },
  {
    id: 128,
    name: "Rowing Machine",
    cubicFeet: 35,
    section: "Exercise Equipment",
    count: 0,
  },
  {
    id: 129,
    name: "Treadmill/ Bike/ Stepper",
    cubicFeet: 45,
    section: "Exercise Equipment",
    count: 0,
  },
  {
    id: 130,
    name: "Weight Bench",
    cubicFeet: 20,
    section: "Exercise Equipment",
    count: 0,
  },






  {
    id: 131,
    name: "Bicyle",
    cubicFeet: 15,
    section: "Outside",
    count: 0,
  },
  {
    id: 132,
    name: "Bird Bath/ Table",
    cubicFeet: 20,
    section: "Outside",
    count: 0,
  },
  {
    id: 133,
    name: "BBQ",
    cubicFeet: 20,
    section: "Outside",
    count: 0,
  },
  {
    id: 134,
    name: "Child Ride on Toy",
    cubicFeet: 8,
    section: "Outside",
    count: 0,
  },
  {
    id: 135,
    name: "Child Sand Pit",
    cubicFeet: 25,
    section: "Outside",
    count: 0,
  },
  {
    id: 136,
    name: "Child Climb/ Slide",
    cubicFeet: 50,
    section: "Outside",
    count: 0,
  },
  {
    id: 137,
    name: "Deck Chair",
    cubicFeet: 5,
    section: "Outside",
    count: 0,
  },
  {
    id: 138,
    name: "Dustbin",
    cubicFeet: 4.5,
    section: "Outside",
    count: 0,
  },
  {
    id: 139,
    name: "Extension Ladder",
    cubicFeet: 20,
    section: "Outside",
    count: 0,
  },
  {
    id: 140,
    name: "Garden Bench",
    cubicFeet: 20,
    section: "Outside",
    count: 0,
  },
  {
    id: 141,
    name: "Garden Chair (Stackable)",
    cubicFeet: 5,
    section: "Outside",
    count: 0,
  },
  {
    id: 142,
    name: "Garden Storage Box",
    cubicFeet: 50,
    section: "Outside",
    count: 0,
  },
  {
    id: 143,
    name: "Garden Table (S)",
    cubicFeet: 10,
    section: "Outside",
    count: 0,
  },
  {
    id: 144,
    name: "Garden Table (M)",
    cubicFeet: 30,
    section: "Outside",
    count: 0,
  },
  {
    id: 145,
    name: "Garden Table (L)",
    cubicFeet: 50,
    section: "Outside",
    count: 0,
  },
  {
    id: 146,
    name: "Garden Tool (per tool)",
    cubicFeet: 1,
    section: "Outside",
    count: 0,
  },
  {
    id: 147,
    name: "Golf Clubs",
    cubicFeet: 7,
    section: "Outside",
    count: 0,
  },
  {
    id: 148,
    name: "Hose and Reel",
    cubicFeet: 3,
    section: "Outside",
    count: 0,
  },
  {
    id: 149,
    name: "Lawn Mower",
    cubicFeet: 12,
    section: "Outside",
    count: 0,
  },
  {
    id: 150,
    name: "Lawn Mower Ride on",
    cubicFeet: 30,
    section: "Outside",
    count: 0,
  },
  {
    id: 151,
    name: "Pair Steps",
    cubicFeet: 10,
    section: "Outside",
    count: 0,
  },
  {
    id: 152,
    name: "Plants",
    cubicFeet: 7.5,
    section: "Outside",
    count: 0,
  },
  {
    id: 153,
    name: "Plant Pot/ Ornament",
    cubicFeet: 5,
    section: "Outside",
    count: 0,
  },
  {
    id: 154,
    name: "Rotary Washing Line",
    cubicFeet: 5,
    section: "Outside",
    count: 0,
  },
  {
    id: 155,
    name: "Sun Lounger",
    cubicFeet: 10,
    section: "Outside",
    count: 0,
  },
  {
    id: 156,
    name: "WheelBarrow",
    cubicFeet: 20,
    section: "Outside",
    count: 0,
  },
  {
    id: 157,
    name: "Work Bench",
    cubicFeet: 7,
    section: "Outside",
    count: 0,
  },



  {
    id: 158,
    name: "Attic Box",
    cubicFeet: 5,
    section: "Other Items",
    count: 0,
  },
  {
    id: 159,
    name: "Hall Chair",
    cubicFeet: 15,
    section: "Other Items",
    count: 0,
  },
  {
    id: 160,
    name: "Hall Table",
    cubicFeet: 10,
    section: "Other Items",
    count: 0,
  },
  {
    id: 161,
    name: "Hall Cabinet",
    cubicFeet: 20,
    section: "Other Items",
    count: 0,
  },
  {
    id: 162,
    name: "Hat Stand",
    cubicFeet: 15,
    section: "Other Items",
    count: 0,
  },
  {
    id: 163,
    name: "Picture",
    cubicFeet: 2,
    section: "Other Items",
    count: 0,
  },
  {
    id: 164,
    name: "Pram/ Pushchair",
    cubicFeet: 12,
    section: "Other Items",
    count: 0,
  },
  {
    id: 165,
    name: "Sewing Machine",
    cubicFeet: 5,
    section: "Other Items",
    count: 0,
  },
  {
    id: 166,
    name: "Box / Bag",
    cubicFeet: 5,
    section: "Other Items",
    count: 0,
  },
  
  
  
  {
    id: 167,
    name: "Monitor",
    cubicFeet: 5,
    section: "Office/ Study",
    count: 0,
  },
  {
    id: 168,
    name: "Box / Bag",
    cubicFeet: 5,
    section: "Lounge / Conservatory",
    count: 0,
  },
  {
    id: 169,
    name: "Box / Bag",
    cubicFeet: 5,
    section: "Dining",
    count: 0,
  },
  {
    id: 170,
    name: "Box / Bag",
    cubicFeet: 5,
    section: "Kitchen / Utility",
    count: 0,
  },
  {
    id: 171,
    name: "Box / Bag",
    cubicFeet: 5,
    section: "Office/ Study",
    count: 0,
  },
  {
    id: 172,
    name: "Box / Bag",
    cubicFeet: 5,
    section: "Outside",
    count: 0,
  },


];