export const initialState = [
  {
    id: 0,
    name: "Armchair",
    cubicFeet: 15,
    section: "Lounge & Conservatory",
    count: 0,
  },
  {
    id: 1,
    name: "Bureau",
    cubicFeet: 15,
    section: "Lounge & Conservatory",
    count: 0,
  },
  {
    id: 2,
    name: "Bookself (S)",
    cubicFeet: 15,
    section: "Lounge & Conservatory",
    count: 0,
  },
  {
    id: 3,
    name: "Bookself (L)",
    cubicFeet: 30,
    section: "Lounge & Conservatory",
    count: 0,
  },
  {
    id: 4,
    name: "Carver",
    cubicFeet: 10,
    section: "Lounge & Conservatory",
    count: 0,
  },
  {
    id: 5,
    name: "China Cabinet (S)",
    cubicFeet: 15,
    section: "Lounge & Conservatory",
    count: 0,
  },
  {
    id: 6,
    name: "China Cabinet (L)",
    cubicFeet: 35,
    section: "Lounge & Conservatory",
    count: 0,
  },
  {
    id: 7,
    name: "Grandfather Clock",
    cubicFeet: 20,
    section: "Lounge & Conservatory",
    count: 0,
  },
  {
    id: 8,
    name: "Floor Lamp",
    cubicFeet: 8,
    section: "Lounge & Conservatory",
    count: 0,
  },
  {
    id: 9,
    name: "Occassional Chair",
    cubicFeet: 10,
    section: "Lounge & Conservatory",
    count: 0,
  },
  {
    id: 10,
    name: "Piano Stool",
    cubicFeet: 5,
    section: "Lounge & Conservatory",
    count: 0,
  },
  {
    id: 11,
    name: "Piano Upright",
    cubicFeet: 40,
    section: "Lounge & Conservatory",
    count: 0,
  },
  {
    id: 12,
    name: "Picutre/ Mirror (S)",
    cubicFeet: 1,
    section: "Lounge & Conservatory",
    count: 0,
  },
  {
    id: 13,
    name: "Picture/ Mirror (L)",
    cubicFeet: 3,
    section: "Lounge & Conservatory",
    count: 0,
  },
  {
    id: 14,
    name: "Pouffe",
    cubicFeet: 10,
    section: "Lounge & Conservatory",
    count: 0,
  },
  {
    id: 15,
    name: "Rocking Chair",
    cubicFeet: 20,
    section: "Lounge & Conservatory",
    count: 0,
  },
  {
    id: 16,
    name: "Rug (S)",
    cubicFeet: 5,
    section: "Lounge & Conservatory",
    count: 0,
  },
  {
    id: 17,
    name: "Rug (L)",
    cubicFeet: 10,
    section: "Lounge & Conservatory",
    count: 0,
  },
  {
    id: 18,
    name: "Settee - 1 Seat",
    cubicFeet: 25,
    section: "Lounge & Conservatory",
    count: 0,
  },
  {
    id: 19,
    name: "Settee - 2 Seat",
    cubicFeet: 45,
    section: "Lounge & Conservatory",
    count: 0,
  },
  {
    id: 20,
    name: "Settee - 3 Seat",
    cubicFeet: 60,
    section: "Lounge & Conservatory",
    count: 0,
  },
  {
    id: 21,
    name: "Sideboard (S)",
    cubicFeet: 20,
    section: "Lounge & Conservatory",
    count: 0,
  },
  {
    id: 22,
    name: "Sideboard (L)",
    cubicFeet: 40,
    section: "Lounge & Conservatory",
    count: 0,
  },




  {
    id: 23,
    name: "CD Stand",
    cubicFeet: 5,
    section: "Living Area",
    count: 0,
  },
  {
    id: 24,
    name: "Coffee Table",
    cubicFeet: 10,
    section: "Living Area",
    count: 0,
  },
  {
    id: 25,
    name: "Mirror",
    cubicFeet: 3,
    section: "Living Area",
    count: 0,
  },
  {
    id: 26,
    name: "Music Cabinet",
    cubicFeet: 15,
    section: "Living Area",
    count: 0,
  },
  {
    id: 27,
    name: "Nest Tables",
    cubicFeet: 10,
    section: "Living Area",
    count: 0,
  },
  {
    id: 28,
    name: "Picture/ Mirror (S)",
    cubicFeet: 1,
    section: "Living Area",
    count: 0,
  },
  {
    id: 29,
    name: "Picture/ Mirror (L)",
    cubicFeet: 3,
    section: "Living Area",
    count: 0,
  },
  {
    id: 30,
    name: "Stool",
    cubicFeet: 5,
    section: "Living Area",
    count: 0,
  },
  {
    id: 31,
    name: "TV",
    cubicFeet: 10,
    section: "Living Area",
    count: 0,
  },
  {
    id: 32,
    name: "TV Stand",
    cubicFeet: 10,
    section: "Living Area",
    count: 0,
  },
  {
    id: 33,
    name: "Boxes/ Bags",
    cubicFeet: 5,
    section: "Living Area",
    count: 0,
  },
  



  
  {
    id: 34,
    name: "Bookshelf (S)",
    cubicFeet: 15,
    section: "Dining",
    count: 0,
  },
  {
    id: 35,
    name: "Bookshelf (L)",
    cubicFeet: 30,
    section: "Dining",
    count: 0,
  },
  {
    id: 36,
    name: "Dining Chair",
    cubicFeet: 5,
    section: "Dining",
    count: 0,
  },
  {
    id: 37,
    name: "Dining Table (S)",
    cubicFeet: 30,
    section: "Dining",
    count: 0,
  },
  {
    id: 38,
    name: "Dining Table (M)",
    cubicFeet: 40,
    section: "Dining",
    count: 0,
  },
  {
    id: 39,
    name: "Dining Table (L)",
    cubicFeet: 50,
    section: "Dining",
    count: 0,
  },
  {
    id: 40,
    name: "Picture/ Mirror (S)",
    cubicFeet: 1,
    section: "Dining",
    count: 0,
  },
  {
    id: 41,
    name: "Picture/ Mirror (L)",
    cubicFeet: 3,
    section: "Dining",
    count: 0,
  },
  {
    id: 42,
    name: "Settle Chair",
    cubicFeet: 30,
    section: "Dining",
    count: 0,
  },
  {
    id: 43,
    name: "Church Style Pew",
    cubicFeet: 30,
    section: "Dining",
    count: 0,
  },
  {
    id: 44,
    name: "Sideboard (S)",
    cubicFeet: 20,
    section: "Dining",
    count: 0,
  },
  {
    id: 45,
    name: "Sideboard (M)",
    cubicFeet: 30,
    section: "Dining",
    count: 0,
  },
  {
    id: 46,
    name: "Sideboard (L)",
    cubicFeet: 40,
    section: "Dining",
    count: 0,
  },
  {
    id: 47,
    name: "TV",
    cubicFeet: 10,
    section: "Dining",
    count: 0,
  },
  {
    id: 48,
    name: "Welsh Dresser",
    cubicFeet: 50,
    section: "Dining",
    count: 0,
  },  






  {
    id: 49,
    name: "Bar Stool",
    cubicFeet: 10,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 50,
    name: "Bookshelf (S)",
    cubicFeet: 15,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 51,
    name: "Bookshelf (L)",
    cubicFeet: 30,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 52,
    name: "Butchers Block",
    cubicFeet: 18,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 53,
    name: "Cooker",
    cubicFeet: 18,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 54,
    name: "Clothes Horse",
    cubicFeet: 5,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 55,
    name: "Dishwasher",
    cubicFeet: 18,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 56,
    name: "Dryer",
    cubicFeet: 18,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 57,
    name: "Freezer, Chest",
    cubicFeet: 18,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 58,
    name: "Freezer, Upright",
    cubicFeet: 34,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 59,
    name: "Fridge/Freezer",
    cubicFeet: 36,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 60,
    name: "Fridge - American",
    cubicFeet: 60,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 61,
    name: "Fridge - beer",
    cubicFeet: 5,
    section: "Kitchen / Utility",
    count: 0,
  },  
  {
    id: 61,
    name: "Fridge - under counter",
    cubicFeet: 18,
    section: "Kitchen / Utility",
    count: 0,
  },  

];